###
POST http://localhost:8000/api/users
Content-Type: application/json

{
    "email": "ejemploss@gmail.com",
    "password": "123456",
    "name": "Damian",
    "surname": "Gonzalez",
    "address": "asd 4305",
    "phonenumber":4353454334
}

###
GET http://localhost:8000/api/users
Content-Type: application/json

###
DELETE http://localhost:8000/api/users/6258ecfec9f55a495d03716f
Content-Type: application/json

###
PUT http://localhost:8000/api/users/6258ecb61eab7e4ac5a0d3dd
Content-Type: application/json

{
    "name":"Jhon Doe"
}